let
    Source = Excel.Workbook(File.Contents(MEPSDataFolder & "h248a.xlsx"), null, true),
    H248A_Sheet = Source{[Item="H248A",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(H248A_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DUID", Int64.Type}, {"PID", Int64.Type}, {"DUPERSID", Int64.Type}, {"DRUGIDX", Int64.Type}, {"RXRECIDX", type text}, {"LINKIDX", Int64.Type}, {"PANEL", Int64.Type}, {"PURCHRD", Int64.Type}, {"RXBEGMM", Int64.Type}, {"RXBEGYRX", Int64.Type}, {"RXNAME", type text}, {"RXDRGNAM", type text}, {"RXNDC", Int64.Type}, {"RXQUANTY", type number}, {"RXFORM", type text}, {"RXFRMUNT", type text}, {"RXSTRENG", type text}, {"RXSTRUNT", type text}, {"RXDAYSUP", Int64.Type}, {"PHARTP1", Int64.Type}, {"PHARTP2", Int64.Type}, {"PHARTP3", Int64.Type}, {"PHARTP4", Int64.Type}, {"PHARTP5", Int64.Type}, {"PHARTP6", Int64.Type}, {"RXFLG", Int64.Type}, {"IMPFLAG", Int64.Type}, {"PCIMPFLG", Int64.Type}, {"DIABEQUIP", Int64.Type}, {"INPCFLG", Int64.Type}, {"TC1", Int64.Type}, {"TC1S1", Int64.Type}, {"TC1S1_1", Int64.Type}, {"TC1S1_2", Int64.Type}, {"TC1S2", Int64.Type}, {"TC1S2_1", Int64.Type}, {"TC1S3", Int64.Type}, {"TC1S3_1", Int64.Type}, {"TC2", Int64.Type}, {"TC2S1", Int64.Type}, {"TC2S1_1", Int64.Type}, {"TC2S1_2", Int64.Type}, {"TC2S2", Int64.Type}, {"TC3", Int64.Type}, {"TC3S1", Int64.Type}, {"TC3S1_1", Int64.Type}, {"RXSF23X", type number}, {"RXMR23X", type number}, {"RXMD23X", type number}, {"RXPV23X", type number}, {"RXVA23X", Int64.Type}, {"RXTR23X", Int64.Type}, {"RXOF23X", Int64.Type}, {"RXSL23X", Int64.Type}, {"RXWC23X", Int64.Type}, {"RXOT23X", Int64.Type}, {"RXXP23X", type number}, {"PERWT23F", type number}, {"VARSTR", Int64.Type}, {"VARPSU", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"PHARTP1", "PHARTP2", "PHARTP3", "PHARTP4", "PHARTP5", "PHARTP6", "RXFLG", "IMPFLAG", "PCIMPFLG", "INPCFLG", "RXSF23X", "RXMR23X", "RXMD23X", "RXPV23X", "RXVA23X", "RXTR23X", "RXOF23X", "RXSL23X", "RXWC23X", "RXOT23X", "RXXP23X", "VARSTR", "VARPSU", "TC1", "TC1S1", "TC1S1_1", "TC1S1_2", "TC1S2", "TC1S2_1", "TC1S3", "TC1S3_1", "TC2", "TC2S1", "TC2S1_1", "TC2S1_2", "TC2S2", "TC3", "TC3S1", "TC3S1_1" , "PANEL", "PURCHRD", "RXNDC" , "RXDRGNAM" , "RXFRMUNT" , "RXSTRENG" , "RXSTRUNT" , "DIABEQUIP", "RXBEGMM" , "RXBEGYRX" , "RXQUANTY"}),
    #"Filtered Rows2" = Table.TransformColumns(#"Removed Columns",{{"RXNAME", each if _ = "-15" then null else _, type text},{"RXFORM", each if _ = "-15" then null else _, type text}}),
    #"Filtered Rows3" = Table.TransformColumns(#"Filtered Rows2",{{"RXDAYSUP", each if _ < 0 then null else _, type number}})
in
    #"Filtered Rows3"
